#!/bin/bash

shellscipt=`basename $0`
usage="Usage: $shellscript [-on] [-off]"

if [ $# -eq 0 ] ; then
  echo $usage

elif [ "$1" = "-on" ] ; then
  xrandr --output VGA1 --mode 1280x1024 --left-of LVDS1

elif [ "$1" = "-off" ] ; then
  xrandr --output VGA1 --off
  xrandr --output LVDS1 --mode 1366x768
  pkill conky
  conky &
else
  echo $usage
fi
