#!/bin/bash

a=`basename $0`
usage="Usage: $a [-on] [-off]"

if [ $# -eq 0 ] ; then
  echo $usage

elif [ "$1" = "-on" ] ; then
  xrandr --output VGA1 --mode 1280x1024 --left-of LVDS1

elif [ "$1" = "-off" ] ; then
  xrandr --output VGA1 --off

else
  echo $usage
fi
