#!/bin/bash

# create array
array=(11 32 2 3 41 5 6)

# Add value to array
array[4]=1.6

# first emelement of the array
echo "$array"  
echo "${array[0]}"

# loop through an array
for i in ${array[*]}; do
		echo "$i";
	done

# indexes
for i in ${!array[@]}; do
		echo "$i";
	done
	
# number of items in array
echo "${#array[@]}"

# Delete element
unset 'array[1]'
	
# Delete array
unset array
