#!/bin/bash
set -x
SD_CARD="/mnt/data"
LIMIT=60

getPercentageOfSD_CARD(){
	PERCENTAGE=$(df -h | grep "$FOLDER" | awk '{ print $5}' | sed 's/%//')

	INT='^[0-9]+$'

	if ! [[ $PERCENTAGE =~ $INT ]] ; then
		echo "[!] Error, Could not calculate" >&2; exit 1
	else
		echo "$PERCENTAGE"
	fi
}

removeOldestFile(){
	OLDEST_FILE=$(find $FOLDER -type f -printf '%T+ %p\n' | sort | head -n 1)
	echo "$OLDEST_FILE"
	}

#if [ $(getPercentageOfFolder) -gt "$LIMIT" ]; then
#	removeOldestFile
#fi
