#!/bin/bash

# How many seconds have left until next 5-minute-cyclic cron job?
# 
# The script exits if started at the same time when the cron job is scheduled

# EPOCH TIME
# date +%s -> number of SECONDS that have elapsed since 00:00:00 Thursday, 1 January 1970
# Thank you for berndbausch from www.linuxquestions.org !

DIFF=$((300-$(date +%s)%300))

if [ "$R" -eq 300 ];then
	exit 1
fi

echo "$DIFF"

exit 0
