#!/bin/bash
#set -x
SD_CARD="/mnt/data"
LIMIT=97

getPercentageOfSD_CARD(){
	PERCENTAGE=$(df -h | grep "$SD_CARD" | awk '{ print $5}' | sed 's/%//')

	INT='^[0-9]+$'

	if ! [[ "$PERCENTAGE" =~ $INT ]] ; then
		echo "[!] Error, Could not calculate" >&2; exit 2
	else
		echo "$PERCENTAGE"
	fi
}

removeOldestFile(){
	OLDEST_FILE=$(find $SD_CARD -type f | sort | head -n 1)
	#rm -rf "$OLDEST_FILE"
	echo "$OLDEST_FILE"
	}

main(){
	if [ ! -d "$SD_CARD" ]; then
		echo "[!] Does not exist" >&2; exit 1
	fi

	if [ "$(getPercentageOfSD_CARD)" -gt "$LIMIT" ]; then
		removeOldestFile
	fi
}

main
